---
# tasks file for java8base
- name: Removing old version of JAVA from Amazon Linux
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Removing old version of JAVA SDK from Amazon Linux
  yum:
    name: java-1.7.0-openjdk-devel
    state: absent

- name: Install specific supported version of JAVA
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Install specific supported version of JAVA SDK
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
